### ISSUE TITLE
Pickle files generation

### ISSUE THREAD

**Issue by dkoguciuk** [Suoivy/LPD-net#1]
Hi!

I am trying to follow your code and prepare the training pickles, but after running this command:

```
# For network evaluation
python generate_test_sets.py
```

I've got:

```
23
['2014-11-14-16-34-33', '2014-11-18-13-20-12', '2014-12-02-15-30-08', '2014-12-09-13-21-02', '2014-12-10-18-10-50', '2014-12-12-10-45-15', '2014-12-16-09-14-09', '2014-12-16-18-44-24', '2015-02-03-08-45-10', '2015-02-10-11-58-05', '2015-02-13-09-16-26', '2015-02-17-14-42-12', '2015-03-10-14-18-10', '2015-03-17-11-08-44', '2015-05-19-14-06-38', '2015-06-09-15-06-29', '2015-08-12-15-04-18', '2015-08-13-16-02-58', '2015-08-14-14-54-57', '2015-08-28-09-50-22', '2015-10-30-13-52-14', '2015-11-12-11-22-05', '2015-11-13-10-28-08']
2014-11-14-16-34-33
Traceback (most recent call last):
  File "generate_test_sets.py", line 117, in <module>
    construct_query_and_database_sets(base_path, runs_folder, folders, featurecloud_fols, "pointcloud_locations_20m.csv", p_dict["oxford"], "oxford")
  File "generate_test_sets.py", line 66, in construct_query_and_database_sets
    test_tree = KDTree(df_test[['northing','easting']])
  File "sklearn/neighbors/_binary_tree.pxi", line 1071, in sklearn.neighbors._kd_tree.BinaryTree.__init__
ValueError: X is an empty array
```

Then, I've compared your `generate_test_sets.py` and `generate_test_sets.py` from the original PointNetVLAD repository, and the only significant difference is a change from:

```
#####For training and test data split#####
x_width=150
y_width=150
```

to:

```
#####For training and test data split#####
x_width=1.5
y_width=1.5
```

I didn't see any mention of testing procedure change in the paper, is that a bug? After changing x/y_width back to 150 the code runs successfully.

**Comment by chn52979** [comment]
hi, Have you solved the problem？

**Comment by dkoguciuk** [comment]
Hi @chn52979 , since the authors did not respond, I've just assumed it's a bug. There were a couple of more bugs, which I've fixed, you can refer to my repo for fixed version: https://github.com/dkoguciuk/attentive-netvlad/tree/master/LPD-net

**Comment by Suoivy** [comment]
Hi @dkoguciuk,
Sorry for the late reply to your issue. According to your reply, you have solved this problem perfectly, and your modification is correct. 
In  `generate_test_sets.py`, modify
from
```
#####For training and test data split#####
x_width=1.5
y_width=1.5
```
to
```
#####For training and test data split#####
x_width=150
y_width=150
```
This problem is caused by uploading the wrong version, which is used for evaluation of the KITTI dataset, so the threshold setting is different from Oxford RobotCar. There is also another issue that needs to be modified in `generating_queries/generate_training_tuples_baseline.py`, modify the #line 22
from
`index_list=range(len(all_folders)-1)`
to
` index_list=range(len(all_folders))`

Hi, @chn52979, I have modified the relevant questions and re-uploaded the code, please be aware.

**Comment by dkoguciuk** [comment]
Hi @Suoivy,

thanks for the response! I did find this `modify the #line 22` the hard way and spend some time fixing it. Hope no one will have this problem anymore. Either way, good job with the paper and the repo @Suoivy!

Best,
D

**Comment by Suoivy** [comment]
Hi @dkoguciuk ,
Sorry for that and best regard.
Suo
